---
title: Cristian Granda
description: Software Engineer / Game Designer
domain: https://cristianbgp.com
language: en
repository: https://github.com/cristianbgp/personal-site/
email: cristian.granda.pastor@gmail.com
social:
  github: cristianbgp
  twitter: cristianbgp
navigation:
  - name: Projects
    path: /projects/
incremental: false
analytics: UA-139257083-1
