---
title: Cristian Granda
description: Game Designer
domain: https://cristianbgp.com
language: es
repository: https://github.com/cristianbgp/personal-site/
email: cristian.granda.pastor@gmail.com
social:
  github: cristianbgp
  twitter: cristianbgp
incremental: false
analytics: UA-139257083-1
